In [1]:
from tensorflow import keras
import matplotlib.pyplot as plt

In [2]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

In [3]:
import cv2

In [4]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

170508288/170498071 [==============================] - 2s 0us/step


In [5]:
x_train.shape,x_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [6]:
x_train = x_train/255.0
x_test = x_test/255.0

In [7]:
nsamples, nx, ny, nrgb = x_train.shape
x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))

In [8]:
nsamples, nx, ny, nrgb = x_test.shape
x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [10]:
model=RandomForestClassifier()

In [11]:
model.fit(x_train2,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier()

In [12]:
y_pred=model.predict(x_test2)
y_pred

array([6, 8, 8, ..., 5, 5, 7], dtype=uint8)

In [13]:
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))


              precision    recall  f1-score   support

           0       0.57      0.54      0.56      1046
           1       0.55      0.53      0.54      1050
           2       0.33      0.36      0.34       913
           3       0.27      0.34      0.30       784
           4       0.40      0.39      0.39      1017
           5       0.38      0.41      0.40       930
           6       0.57      0.48      0.52      1193
           7       0.46      0.51      0.48       891
           8       0.62      0.58      0.60      1054
           9       0.53      0.48      0.50      1122

    accuracy                           0.47     10000
   macro avg       0.47      0.46      0.46     10000
weighted avg       0.48      0.47      0.47     10000



In [14]:
confusion_matrix(y_pred,y_test)

array([[570,  28, 111,  47,  52,  30,   8,  55,  93,  52],
       [ 33, 553,  44,  51,  21,  25,  30,  40,  80, 173],
       [ 62,  27, 326,  85, 157,  91,  89,  44,  20,  12],
       [ 11,  29,  78, 268,  57, 167,  61,  56,  26,  31],
       [ 35,  20, 151,  64, 395,  84, 115, 112,  21,  20],
       [ 16,  30,  75, 184,  53, 383,  49,  89,  29,  22],
       [ 24,  43, 108, 144, 134,  84, 573,  44,  10,  29],
       [ 28,  33,  55,  59,  82,  79,  22, 456,  24,  53],
       [160,  66,  23,  24,  29,  30,  10,  21, 616,  75],
       [ 61, 171,  29,  74,  20,  27,  43,  83,  81, 533]])

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
knn=KNeighborsClassifier(n_neighbors=7)

In [17]:
knn.fit(x_train2,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [18]:
y_pred_knn=knn.predict(x_test2)
y_pred_knn

array([2, 8, 8, ..., 5, 6, 4], dtype=uint8)

In [19]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test))


              precision    recall  f1-score   support

           0       0.52      0.40      0.45      1299
           1       0.20      0.70      0.30       280
           2       0.44      0.22      0.29      2013
           3       0.20      0.28      0.23       707
           4       0.52      0.23      0.32      2222
           5       0.20      0.40      0.27       504
           6       0.27      0.35      0.30       761
           7       0.20      0.70      0.31       281
           8       0.69      0.39      0.50      1749
           9       0.14      0.73      0.23       184

    accuracy                           0.34     10000
   macro avg       0.34      0.44      0.32     10000
weighted avg       0.45      0.34      0.35     10000



In [20]:
confusion_matrix(y_pred_knn,y_test)

array([[518, 118, 110,  66,  60,  63,  22,  78, 112, 152],
       [  7, 195,   2,   5,   0,   2,   1,   8,  10,  50],
       [118, 124, 437, 243, 268, 225, 271, 185,  47,  95],
       [ 12,  51,  50, 199,  33, 156,  56,  57,  34,  59],
       [ 46, 173, 250, 214, 521, 201, 319, 294,  69, 135],
       [  5,  32,  24, 102,  14, 204,  32,  60,  12,  19],
       [ 30,  55,  65, 108,  44,  80, 265,  48,  14,  52],
       [  5,   8,   7,  11,  11,  10,   1, 196,   7,  25],
       [255, 223,  53,  51,  48,  53,  32,  68, 688, 278],
       [  4,  21,   2,   1,   1,   6,   1,   6,   7, 135]])

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
dtc=DecisionTreeClassifier()

In [23]:
dtc.fit(x_train2,y_train)

DecisionTreeClassifier()

In [24]:
y_pred_dtc=dtc.predict(x_test2)
y_pred_dtc

array([7, 1, 9, ..., 2, 5, 3], dtype=uint8)

In [25]:
accuracy_score(y_pred_dtc,y_test)
print(classification_report(y_pred_dtc,y_test))

              precision    recall  f1-score   support

           0       0.36      0.33      0.35      1089
           1       0.24      0.26      0.25       929
           2       0.23      0.22      0.22      1066
           3       0.17      0.18      0.17       933
           4       0.23      0.22      0.23      1057
           5       0.22      0.22      0.22       969
           6       0.29      0.29      0.29       988
           7       0.26      0.28      0.27       929
           8       0.39      0.37      0.38      1045
           9       0.29      0.29      0.29       995

    accuracy                           0.27     10000
   macro avg       0.27      0.27      0.27     10000
weighted avg       0.27      0.27      0.27     10000



In [26]:
confusion_matrix(y_pred_dtc,y_test)

array([[361,  78, 101,  75,  68,  54,  46,  75, 137,  94],
       [ 73, 245,  41,  59,  49,  57,  49,  88,  98, 170],
       [ 91,  75, 231, 105, 155, 113, 118,  82,  40,  56],
       [ 47,  84,  80, 166,  85, 145, 119,  95,  49,  63],
       [ 64,  64, 137, 120, 235, 100, 148,  98,  50,  41],
       [ 48,  49, 112, 132, 108, 218,  96, 109,  49,  48],
       [ 33,  54, 116, 141, 115,  96, 288,  64,  29,  52],
       [ 51,  67,  89,  92,  97,  96,  57, 262,  43,  75],
       [148, 113,  44,  51,  39,  66,  28,  57, 389, 110],
       [ 84, 171,  49,  59,  49,  55,  51,  70, 116, 291]])

In [27]:
from sklearn.naive_bayes import GaussianNB

In [28]:
nb=GaussianNB()

In [29]:
nb.fit(x_train2,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [30]:
y_pred_nb=nb.predict(x_test2)
y_pred_nb

array([6, 8, 8, ..., 6, 5, 4], dtype=uint8)

In [31]:
accuracy_score(y_pred_nb,y_test)
print(classification_report(y_pred_nb,y_test))

              precision    recall  f1-score   support

           0       0.49      0.27      0.35      1817
           1       0.17      0.41      0.24       405
           2       0.08      0.19      0.12       443
           3       0.08      0.25      0.12       305
           4       0.42      0.24      0.30      1737
           5       0.26      0.31      0.29       840
           6       0.47      0.25      0.33      1846
           7       0.13      0.42      0.20       310
           8       0.47      0.39      0.42      1219
           9       0.41      0.38      0.39      1078

    accuracy                           0.30     10000
   macro avg       0.30      0.31      0.28     10000
weighted avg       0.39      0.30      0.32     10000



In [32]:
confusion_matrix(y_pred_nb,y_test)

array([[494, 141, 225, 163,  86, 156, 106, 134, 168, 144],
       [ 20, 166,  24,  36,   8,  17,   2,  24,  41,  67],
       [ 39,  24,  83,  54,  57,  55,  60,  36,  18,  17],
       [ 10,  31,  15,  76,  26,  51,  18,  41,  17,  20],
       [ 84,  66, 292, 151, 417, 167, 228, 228,  56,  48],
       [ 34,  72,  48, 129,  38, 264,  46,  94,  83,  32],
       [ 50, 192, 209, 262, 265, 159, 467, 102,  39, 101],
       [  9,  19,  21,  26,  22,  36,  15, 131,   8,  23],
       [200, 121,  54,  34,  50,  57,  19,  72, 471, 141],
       [ 60, 168,  29,  69,  31,  38,  39, 138,  99, 407]])

In [33]:
from google.colab.patches import cv2_imshow

In [34]:
img_path='/content/bird.jpg'

In [35]:
img_arr=cv2.imread(img_path)
img_arr=cv2.resize(img_arr,(32,32))
cv2.imwrite(img_path, img_arr)


True

In [36]:
nx, ny, nrgb = img_arr.shape
img_arr2 = img_arr.reshape(1,(nx*ny*nrgb))

In [37]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [38]:
ans=model.predict(img_arr2)
print(classes[ans[0]])


bird
